startingbusiness_app/blog/forms.py
"""
This file is used for the definitions of forms used in the blog blueprint. It comprises the forms for the blog page,
create a new post and modify/delete it.
"""

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, RadioField
from wtforms.validators import DataRequired, Length


class BlogPage(FlaskForm):
    # add_post_button = SubmitField('Write a new post')
    filter_keyword = StringField('Keyword search')
    sort_by = RadioField('Sort posts by:', choices=[('date_new', 'Date - Newest'),
                                                    ('date_old', 'Date - Oldest'),
                                                    ('title', 'Title')], default='date_new')


class CreateNewPost(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=2, max=50)])
    content = TextAreaField('Content', validators=[DataRequired(), Length(min=2, max=500)])
    submit_post = SubmitField('Create Post')


class ModifyPost(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=2, max=50)])
    content = TextAreaField('Content', validators=[DataRequired(), Length(min=2, max=500)])
    submit_post = SubmitField('Update Post')


class Post(FlaskForm):
    pass


class DeletePost(FlaskForm):
    pass

startingbusiness_app/blog/routes.py
"""
This file was developed to establish the routes for the blog blueprint.

Part of the overall structure was based on the tutorial videos of Corey Schafer for 'flask tutorial'
(https://www.youtube.com/playlist?list=PL-osiE80TeTs4UjLw5MM6OjgkjFeUxCYH), even though it was modified to fit the
purpose of the web app.
"""

from flask import Blueprint, render_template, flash, redirect, url_for, request, abort
from flask_login import login_required, current_user
from flask_mail import Message
from sqlalchemy import or_
from sqlalchemy.exc import IntegrityError
from startingbusiness_app import db, mail
from startingbusiness_app.blog.forms import CreateNewPost, ModifyPost, Post, BlogPage
from startingbusiness_app.models import Blog, User

blog_bp = Blueprint('blog', __name__, template_folder='templates', static_folder='static')


@blog_bp.route('', methods=['GET', 'POST'])
def blog():
    posts = Blog.query.order_by(Blog.date_posted.desc()).all()
    blog_form = BlogPage()
    word = blog_form.filter_keyword.data
    sort = blog_form.sort_by.data
    if blog_form.validate_on_submit():
        if sort == 'date_new':
            posts = Blog.query.filter(or_(Blog.title.contains(word), Blog.content.contains(word))).order_by(
                Blog.date_posted.desc())
            sort_label = 'Date Added - Newest'
        elif sort == 'date_old':
            posts = Blog.query.filter(or_(Blog.title.contains(word), Blog.content.contains(word))).order_by(
                Blog.date_posted.asc())
            sort_label = 'Date Added - Oldest'
        elif sort == 'title':
            posts = Blog.query.filter(or_(Blog.title.contains(word), Blog.content.contains(word))).order_by(
                Blog.title.asc())
            sort_label = 'Title'
        blog_form.filter_keyword.data = ""
        blog_form.sort_by.data = "date_new"
        if sort and not word:
            flash(f"Posts filtered by {sort_label}", "info")
        else:
            flash(f"Posts filtered by {sort_label} and {word}'", "info")
        return render_template('blog/blog.html', form=blog_form, posts=posts, title='Blog')

    return render_template('blog/blog.html', form=blog_form, posts=posts, title='Blog')


def send_post_email(user, post_email):
    message = Message('Starting a Business App - New Post', recipients=[user.email])
    message.body = f'''Hello {user.first_name},
thank you for adding a new post to the blog!

Here is your post:
    TITLE: {post_email.title}
    
    MAIN BODY:
    {post_email.content}
'''
    mail.send(message)


@blog_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    post_form = CreateNewPost()
    if post_form.validate_on_submit():
        new_post_action = Blog(title=post_form.title.data, content=post_form.content.data, author=current_user)
        try:
            db.session.add(new_post_action)
            db.session.commit()
            send_post_email(current_user, new_post_action)
            flash('Your post has been published successfully', 'success')
        except IntegrityError:
            db.session.rollback()
            flash(f'Error, unable to publish the post.', 'error')
        return redirect(url_for('blog.blog'))
    return render_template('blog/create_update_post.html', form=post_form, title='New Post')


@blog_bp.route("/post/<int:post_id>")
def post(post_id):
    post_form = Post()
    single_post = Blog.query.get_or_404(post_id)
    return render_template('blog/post.html', title=single_post.title, post=single_post, form=post_form)


@blog_bp.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def modify_post(post_id):
    modify_post_action = Blog.query.get_or_404(post_id)
    if modify_post_action.author != current_user:
        abort(403)
    post_form = ModifyPost()
    if post_form.validate_on_submit():
        modify_post_action.title = post_form.title.data
        modify_post_action.content = post_form.content.data
        try:
            db.session.add(modify_post_action)
            db.session.commit()
            flash('Your post has been updated successfully', 'success')
        except IntegrityError:
            db.session.rollback()
            flash(f'Error, unable to update the post.', 'error')
        return redirect(url_for('blog.post', post_id=modify_post_action.id))
    elif request.method == 'GET':
        post_form.title.data = modify_post_action.title
        post_form.content.data = modify_post_action.content
    return render_template('blog/create_update_post.html', title='Update Post', form=post_form, legend='Update Post')


@blog_bp.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    delete_post_action = Blog.query.get_or_404(post_id)
    post_form = BlogPage()
    if delete_post_action.author != current_user:
        abort(403)
    try:
        db.session.delete(delete_post_action)
        db.session.commit()
        flash('Your post has been deleted!', 'success')
        redirect(url_for('blog.blog'))
    except IntegrityError:
        db.session.rollback()
        flash(f'Error, unable to delete the post.', 'error')
    posts = Blog.query.order_by(Blog.date_posted.desc()).all()
    return render_template('blog/blog.html', title='Update Post', form=post_form, posts=posts, legend='Update Post')


@blog_bp.route("/user/<string:email>")
def user_posts(email):
    user = User.query.filter_by(email=email).first_or_404()
    posts = Blog.query.filter_by(author=user).order_by(Blog.date_posted.desc())
    blog_form = BlogPage()
    return render_template('blog/blog.html', form=blog_form, posts=posts, user=user)

startingbusiness_app/blog/templates/blog/blog.html
<head>
    <link rel="stylesheet" type="text/css" href="{{ url_for('blog.static', filename='css/blog.css') }}">
</head>

{% extends 'layout.html' %}
{%  block content %}
    <div class="row">
    {# Version using _formhelpers see: https://flask.palletsprojects.com/en/2.0.x/patterns/wtforms/#forms-in-templates #}
    <div class="col col-md-2" style="float:left; align-content: start">
        <div class="align-content-start">
            <div>
                <a class="btn btn-primary btn-lg mb-3" href="{{ url_for('blog.new_post') }}">Write a New Post</a>
            </div>
            <form method=post action="{{ url_for('blog.blog') }}" autocomplete="off">
                {{ form.csrf_token }}
                <div class="form-group mb-3">
                    {{ form.filter_keyword.label(class="form-control-label") }}
                    {{ form.filter_keyword(class="form-control") }}
                    <small class="text-sm-end text-muted">Press Enter to submit your word search</small>
                </div>
                <div class="form-group mb-3">
                    <div class="row">
                        {{ form.sort_by.label(class="form-control-label") }}
                    </div>
                    {% for subfield in form.sort_by %}
                        {{ subfield }} {{ subfield.label }}
                        <div class="row"></div>
                    {% endfor %}
                    <div class="input-group mb-3">
                    <input type="submit">
                    </div>
                </div>
                <div class="text-sm text-muted">Click on the name of the user to see all the posts by that author</div>
            </form>
        </div>
    </div>
    <div class="container-fluid col col-md-9 ">
        <body>
        {% for post in posts %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                    <h5><a class="mr-2" href="{{ url_for('blog.user_posts', email=post.author.email) }}">{{ post.author.first_name }} {{ post.author.last_name }}</a></h5>

                    <small class="text-muted float-end">{{ post.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>
                    <small class="text-muted d-flex">{{ post.author.email }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
              </div>
            </article>
        {% endfor %}
    </body>
    </div>
    </div>
{% endblock content %}

startingbusiness_app/blog/templates/blog/create_update_post.html
<head>
    <link rel="stylesheet" type="text/css" href="{{ url_for('blog.static', filename='css/blog.css') }}">
</head>

{% extends "layout.html" %}
{% block content %}
    <div class="row justify-content-md-center">
        <div class="col col-md-10 ">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.csrf_token }}
                    <fieldset class="form-group">
                        <h2><legend class="border-bottom mt-2 mb-4">{{title}}</legend></h2>
                        <div class="form-group mb-2">
                            {{ form.title.label(class="form-control-label") }}
                            {{ form.title(class="form-control form-control-lg") }}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.content.label(class="form-control-label") }}
                            {{ form.content(class="form-control") }}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit_post(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

startingbusiness_app/blog/templates/blog/post.html
<head>
    <link rel="stylesheet" type="text/css" href="{{ url_for('blog.static', filename='css/blog.css') }}">
</head>

{% extends 'layout.html' %}
{%  block content %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
            <h5><a class="mr-2" href="{{ url_for('blog.user_posts', email=post.author.email) }}">{{ post.author.first_name }} {{ post.author.last_name }}</a></h5>
            <small class="text-muted float-end">{{ post.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>
            <small class="text-muted d-flex">{{ post.author.email }}</small>
        </div>
          <h2><a class="article-title">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    {% if post.author == current_user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('blog.modify_post', post_id=post.id) }}">Update</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
      </div>
    {% endif %}
    </article>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
              <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
              <div class="modal-body">
                  <h4>{{ post.title }}</h4>
                <p>Are you sure you want to delete this post?</p>
              </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
              <form method=post action="{{ url_for('blog.delete_post', post_id=post.id) }}">
                  {{ form.csrf_token }}
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
    </div>
{% endblock content %}